#!/bin/bash

# Elric Framework - Installation Script
# This script installs the 'elric' command globally on your system

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the absolute path of the project directory
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Elric Framework - Installation${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if uv is installed
if ! command -v uv &> /dev/null; then
    echo -e "${RED}✗ Error: 'uv' is not installed${NC}"
    echo -e "${YELLOW}  Please install uv first: https://github.com/astral-sh/uv${NC}"
    echo -e "${YELLOW}  Quick install: curl -LsSf https://astral.sh/uv/install.sh | sh${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Found uv package manager${NC}"

# Determine installation directory
if [ -w "/usr/local/bin" ]; then
    INSTALL_DIR="/usr/local/bin"
elif [ -w "$HOME/.local/bin" ]; then
    INSTALL_DIR="$HOME/.local/bin"
    mkdir -p "$INSTALL_DIR"
else
    INSTALL_DIR="$HOME/.local/bin"
    mkdir -p "$INSTALL_DIR"
fi

echo -e "${BLUE}→ Installation directory: ${INSTALL_DIR}${NC}"

# Create wrapper script
WRAPPER_SCRIPT="${INSTALL_DIR}/elric"

echo -e "${BLUE}→ Creating wrapper script...${NC}"

cat > "$WRAPPER_SCRIPT" << EOF
#!/bin/bash
# Elric Framework CLI Wrapper
# Auto-generated by install.sh

PROJECT_DIR="${PROJECT_DIR}"

# Change to project directory and run elric with uv
cd "\${PROJECT_DIR}" && uv run elric "\$@"
EOF

# Make wrapper executable
chmod +x "$WRAPPER_SCRIPT"

echo -e "${GREEN}✓ Wrapper script created${NC}"

# Check if installation directory is in PATH
if [[ ":$PATH:" != *":${INSTALL_DIR}:"* ]]; then
    echo ""
    echo -e "${YELLOW}⚠ Warning: ${INSTALL_DIR} is not in your PATH${NC}"
    echo -e "${YELLOW}  Add this line to your ~/.zshrc or ~/.bashrc:${NC}"
    echo -e "${BLUE}  export PATH=\"${INSTALL_DIR}:\$PATH\"${NC}"
    echo ""
    echo -e "${YELLOW}  Then reload your shell:${NC}"
    echo -e "${BLUE}  source ~/.zshrc  # or source ~/.bashrc${NC}"
    echo ""
fi

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  ✓ Installation completed successfully!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}  You can now use the 'elric' command from anywhere:${NC}"
echo -e "${GREEN}    elric --help${NC}"
echo -e "${GREEN}    elric make agent MyAgent${NC}"
echo -e "${GREEN}    elric serve${NC}"
echo ""
echo -e "${BLUE}  Project directory: ${PROJECT_DIR}${NC}"
echo -e "${BLUE}  Wrapper installed: ${WRAPPER_SCRIPT}${NC}"
echo ""
